name: Node.js CI
run-name: "Event Name: ${{ github.event_name }}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.node-version }} - ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies and test
      run: | 
        npm install
        npm test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
  

